#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Push the publication list from cv.yaml into the lab website.

The lab site (sunwhikim-lab-page) hand-writes its markup, so rather than
rewriting the file we replace exactly one delimited region:

    <!-- CV:PUBLICATIONS:START -->  ...generated...  <!-- CV:PUBLICATIONS:END -->

Everything outside the markers is left byte-for-byte alone. If the markers are
missing the script refuses to touch the file and tells you where to add them.

    python scripts/sync_labpage.py --lab ../sunwhikim_lab_page
    python scripts/sync_labpage.py --lab ../sunwhikim_lab_page --check
"""
from __future__ import annotations

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import cvdata  # noqa: E402
from cvdata import PUB_KINDS, stamp  # noqa: E402

START = "<!-- CV:PUBLICATIONS:START -->"
END = "<!-- CV:PUBLICATIONS:END -->"
WARN = ("<!-- generated by sunwhi-cv/scripts/sync_labpage.py from cv.yaml — "
        "edit cv.yaml, not this block -->")


def esc(s) -> str:
    import html
    return html.escape("" if s is None else str(s), quote=True)


# Which buckets the website shows. Conference abstracts stay on the CV only.
SITE_KINDS = ["journal", "preprint"]


def site_rows(d: dict) -> list:
    rows = [p for kind in SITE_KINDS for p in d["publications"][kind]]
    rows.sort(key=lambda p: int(str(p.get("year", 0))[:4] or 0), reverse=True)
    return rows


def _venue(pub: dict) -> str:
    """'Cell Reports 39(10)', 'Nature Communications 16, 1407', 'arXiv:2603.24048'."""
    if pub.get("venue") == "arXiv":
        return esc(pub.get("article") or "arXiv")
    out = esc(pub.get("venue") or "")
    if pub.get("volume"):
        out += " %s" % esc(pub["volume"])
        if pub.get("issue"):
            out += "(%s)" % esc(pub["issue"])
        if pub.get("article") and not pub.get("issue"):
            out += ", %s" % esc(pub["article"])
    elif pub.get("article"):
        out += " %s" % esc(pub["article"])
    return out


def _badges(pub: dict) -> str:
    """The site's own badge vocabulary: 주저자 / 공저자 / 표지 선정."""
    out = []
    role = pub.get("role_kr") or ""
    if "제1저자" in role or "주저자" in role:
        out.append('<span class="pub-badge badge-first">주저자</span>')
    elif "공저자" in role:
        out.append('<span class="pub-badge badge-co">공저자</span>')
    if pub.get("note_kr") and "표지" in pub["note_kr"]:
        out.append('<span class="pub-badge badge-cover">표지 선정</span>')
    return "".join(out)


def render_block(d: dict, indent: str = "      ") -> str:
    """Publication list items in the lab site's existing markup idiom."""
    out = [START, indent + WARN]
    for pub in site_rows(d):
        href = ("https://doi.org/%s" % pub["doi"]) if pub.get("doi") else (pub.get("url") or "")
        title = esc((pub.get("title") or "").rstrip(".")) + "."
        link = ('<a class="pub-link" href="%s" target="_blank" rel="noopener">%s</a>'
                % (esc(href), title)) if href else title
        out.append("\n".join([
            '%s<li class="pub-item">' % indent,
            '%s  <div class="pub-year">%s</div>' % (indent, esc(pub.get("year"))),
            '%s  <div class="pub-title">%s%s</div>' % (indent, link, _badges(pub)),
            '%s  <div class="pub-journal">%s</div>' % (indent, _venue(pub)),
            "%s</li>" % indent,
        ]))
    out.append(indent + END)
    return "\n".join(out)


def sync(lab_dir: str, check: bool = False, source: str | None = None) -> int:
    index = os.path.join(lab_dir, "index.html")
    if not os.path.exists(index):
        sys.stderr.write("no index.html at %s\n" % index)
        return 2

    d = cvdata.load(source)
    html = io.open(index, encoding="utf-8").read()

    if START not in html or END not in html:
        sys.stderr.write(
            "marker block not found in %s\n\n"
            "Add these two comments around the publication list, then re-run:\n"
            "    %s\n    ...\n    %s\n" % (index, START, END))
        return 2

    m = re.search(re.escape(START) + r".*?" + re.escape(END), html, flags=re.S)
    old = m.group(0)
    indent_m = re.search(r"\n([ \t]*)" + re.escape(START), html)
    indent = indent_m.group(1) if indent_m else "          "
    new = render_block(d, indent=indent)

    n = len(site_rows(d))
    updated = html.replace(old, new)

    # The boot animation announces a record count. Keep it honest — it drifted
    # out of step with the list once already, when a paper was dropped during a
    # redesign and the count was left behind.
    updated, hits = re.subn(r"(Mounting publication index \()\d+( records\))",
                            r"\g<1>%d\g<2>" % n, updated)
    if not hits:
        sys.stderr.write("  note: boot-sequence record count not found — skipped\n")

    if updated == html:
        print("lab page publications already in sync (%d entries)" % n)
        return 0

    if check:
        sys.stderr.write("lab page publications are OUT OF SYNC with cv.yaml\n")
        return 1

    io.open(index, "w", encoding="utf-8", newline="\n").write(updated)
    print("updated %s — %d publications (%s), generated %s"
          % (index, n, "/".join(SITE_KINDS), stamp(d)))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync publications into the lab website")
    ap.add_argument("--lab", required=True, help="path to the sunwhikim_lab_page checkout")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if out of sync, change nothing")
    ap.add_argument("--source", default=None, help="path to cv.yaml")
    args = ap.parse_args()
    return sync(args.lab, check=args.check, source=args.source)


if __name__ == "__main__":
    sys.exit(main())
