#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Push the publication list from cv.yaml into the lab website.

The lab site (sunwhikim-lab-page) hand-writes its markup, so rather than
rewriting the file we replace exactly one delimited region:

    <!-- CV:PUBLICATIONS:START -->  ...generated...  <!-- CV:PUBLICATIONS:END -->

Everything outside the markers is left byte-for-byte alone. If the markers are
missing the script refuses to touch the file and tells you where to add them.

    python scripts/sync_labpage.py --lab ../sunwhikim_lab_page
    python scripts/sync_labpage.py --lab ../sunwhikim_lab_page --check
"""
from __future__ import annotations

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import cvdata  # noqa: E402
from cvdata import PUB_KINDS, stamp  # noqa: E402

START = "<!-- CV:PUBLICATIONS:START -->"
END = "<!-- CV:PUBLICATIONS:END -->"
WARN = ("<!-- generated by sunwhi-cv/scripts/sync_labpage.py from cv.yaml — "
        "edit cv.yaml, not this block -->")


def esc(s) -> str:
    import html
    return html.escape("" if s is None else str(s), quote=True)


def render_block(d: dict, indent: str = "          ") -> str:
    """Publication cards in the lab site's existing markup idiom."""
    rows = []
    for kind in PUB_KINDS:
        for pub in d["publications"][kind]:
            rows.append(pub)
    rows.sort(key=lambda p: int(str(p.get("year", 0))[:4] or 0), reverse=True)

    out = [START, indent + WARN]
    for pub in rows:
        venue = esc(pub.get("venue") or "")
        if pub.get("volume"):
            venue += " %s" % esc(pub["volume"])
            if pub.get("issue"):
                venue += "(%s)" % esc(pub["issue"])
        if pub.get("article"):
            venue += ", %s" % esc(pub["article"])
        href = ("https://doi.org/%s" % pub["doi"]) if pub.get("doi") else (pub.get("url") or "")

        card = [
            '%s<article class="pub" data-year="%s" data-kind="%s">' % (
                indent, esc(pub.get("year")), esc(pub.get("kind"))),
            '%s  <span class="pub-year">%s</span>' % (indent, esc(pub.get("year"))),
            '%s  <h3 class="pub-title">%s</h3>' % (
                indent, esc((pub.get("title") or "").rstrip("."))),
        ]
        tags = []
        if pub.get("role_kr"):
            tags.append('<span class="pub-tag">%s</span>' % esc(pub["role_kr"]))
        if pub.get("note_kr") or pub.get("note"):
            tags.append('<span class="pub-tag pub-tag--flag">%s</span>'
                        % esc(pub.get("note_kr") or pub.get("note")))
        if tags:
            card.append('%s  <p class="pub-tags">%s</p>' % (indent, "".join(tags)))
        if href:
            card.append('%s  <p class="pub-venue"><a href="%s" rel="noopener">%s</a></p>'
                        % (indent, esc(href), venue))
        else:
            card.append('%s  <p class="pub-venue">%s</p>' % (indent, venue))
        card.append("%s</article>" % indent)
        out.append("\n".join(card))

    out.append(indent + END)
    return "\n".join(out)


def sync(lab_dir: str, check: bool = False, source: str | None = None) -> int:
    index = os.path.join(lab_dir, "index.html")
    if not os.path.exists(index):
        sys.stderr.write("no index.html at %s\n" % index)
        return 2

    d = cvdata.load(source)
    html = io.open(index, encoding="utf-8").read()

    if START not in html or END not in html:
        sys.stderr.write(
            "marker block not found in %s\n\n"
            "Add these two comments around the publication list, then re-run:\n"
            "    %s\n    ...\n    %s\n" % (index, START, END))
        return 2

    m = re.search(re.escape(START) + r".*?" + re.escape(END), html, flags=re.S)
    old = m.group(0)
    indent_m = re.search(r"\n([ \t]*)" + re.escape(START), html)
    indent = indent_m.group(1) if indent_m else "          "
    new = render_block(d, indent=indent)

    if old == new:
        print("lab page publications already in sync (%d entries)"
              % len(cvdata.all_publications(d)))
        return 0

    if check:
        sys.stderr.write("lab page publications are OUT OF SYNC with cv.yaml\n")
        return 1

    io.open(index, "w", encoding="utf-8", newline="\n").write(html.replace(old, new))
    print("updated %s — %d publications, generated %s"
          % (index, len(cvdata.all_publications(d)), stamp(d)))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync publications into the lab website")
    ap.add_argument("--lab", required=True, help="path to the sunwhikim_lab_page checkout")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if out of sync, change nothing")
    ap.add_argument("--source", default=None, help="path to cv.yaml")
    args = ap.parse_args()
    return sync(args.lab, check=args.check, source=args.source)


if __name__ == "__main__":
    sys.exit(main())
