#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Push CV data into the lab website.

The lab site hand-writes its markup and has a deliberate terminal aesthetic, so
this never rewrites the file. It replaces the contents of named marker blocks:

    <!-- CV:PUBLICATIONS:START -->  ...generated...  <!-- CV:PUBLICATIONS:END -->

Everything outside the markers is left byte-for-byte alone. A block whose
markers are absent is skipped with a note, so the site can adopt them one at a
time.

    python scripts/sync_labpage.py --lab ../sunwhikim_lab_page
    python scripts/sync_labpage.py --lab ../sunwhikim_lab_page --check

The site is NOT a mirror of the CV: it shows what serves a visitor deciding
whether to work with the lab. Teaching tables, committee service and
certifications stay on the CV, which the site links to.
"""
from __future__ import annotations

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import cvdata  # noqa: E402
from cvdata import daterange, stamp  # noqa: E402

WARN = ("<!-- generated by sunwhi-cv/scripts/sync_labpage.py from cv.yaml — "
        "edit cv.yaml, not this block -->")

# Which publication buckets the website shows. Conference abstracts stay on the CV.
SITE_KINDS = ["journal", "preprint"]


def esc(s) -> str:
    import html
    return html.escape("" if s is None else str(s), quote=True)


def site_rows(d: dict) -> list:
    rows = [p for kind in SITE_KINDS for p in d["publications"][kind]]
    rows.sort(key=lambda p: int(str(p.get("year", 0))[:4] or 0), reverse=True)
    return rows


# --------------------------------------------------------------------------
# block renderers — each returns the inner HTML for one marker block
# --------------------------------------------------------------------------

def _venue(pub: dict) -> str:
    """'Cell Reports 39(10)', 'Nature Communications 16, 1407', 'arXiv:2603.24048'."""
    if pub.get("venue") == "arXiv":
        return esc(pub.get("article") or "arXiv")
    out = esc(pub.get("venue") or "")
    if pub.get("volume"):
        out += " %s" % esc(pub["volume"])
        if pub.get("issue"):
            out += "(%s)" % esc(pub["issue"])
        if pub.get("article") and not pub.get("issue"):
            out += ", %s" % esc(pub["article"])
    elif pub.get("article"):
        out += " %s" % esc(pub["article"])
    return out


def _badges(pub: dict) -> str:
    """The site's own badge vocabulary: 주저자 / 공저자 / 표지 선정."""
    out = []
    role = pub.get("role_kr") or ""
    if "제1저자" in role or "주저자" in role:
        out.append('<span class="pub-badge badge-first">주저자</span>')
    elif "공저자" in role:
        out.append('<span class="pub-badge badge-co">공저자</span>')
    if pub.get("note_kr") and "표지" in pub["note_kr"]:
        out.append('<span class="pub-badge badge-cover">표지 선정</span>')
    return "".join(out)


def block_publications(d: dict, i: str) -> list[str]:
    out = []
    for pub in site_rows(d):
        href = ("https://doi.org/%s" % pub["doi"]) if pub.get("doi") else (pub.get("url") or "")
        title = esc((pub.get("title") or "").rstrip(".")) + "."
        link = ('<a class="pub-link" href="%s" target="_blank" rel="noopener">%s</a>'
                % (esc(href), title)) if href else title
        out.append("\n".join([
            '%s<li class="pub-item">' % i,
            '%s  <div class="pub-year">%s</div>' % (i, esc(pub.get("year"))),
            '%s  <div class="pub-title">%s%s</div>' % (i, link, _badges(pub)),
            '%s  <div class="pub-journal">%s</div>' % (i, _venue(pub)),
            "%s</li>" % i,
        ]))
    return out


def block_profile(d: dict, i: str) -> list[str]:
    """The about timeline: appointments then degrees, each with its dates."""
    out = []
    for a in d["appointments"]:
        org = a.get("org_kr") or a.get("org_en", "")
        role = a.get("role_kr") or a.get("role_en", "")
        dept = a.get("dept_kr") or a.get("dept_en", "")
        span = daterange(a.get("start"), a.get("end"), lang="kr")
        out.append("\n".join([
            "%s<li>" % i,
            '%s  <strong>%s</strong>' % (i, esc(org)),
            "%s  %s · %s" % (i, esc(role), esc(dept)),
            '%s  <span class="timeline-when">%s</span>' % (i, esc(span)),
            "%s</li>" % i,
        ]))
    for e in d["education"]:
        org = e.get("org_kr") or e.get("org_en", "")
        deg = e.get("degree_kr") or e.get("degree_en", "")
        dept = e.get("dept_kr") or e.get("dept_en", "")
        span = daterange(e.get("start"), e.get("end"), lang="kr")
        out.append("\n".join([
            "%s<li>" % i,
            '%s  <strong>%s</strong>' % (i, esc(org)),
            "%s  %s · %s" % (i, esc(deg), esc(dept)),
            '%s  <span class="timeline-when">%s</span>' % (i, esc(span)),
            "%s</li>" % i,
        ]))
    return out


def block_software(d: dict, i: str) -> list[str]:
    """Registered software first, then the deployed tools under a sub-label."""
    reg = [s for s in d["software"] if s.get("registration")]
    tools = [s for s in d["software"] if not s.get("registration") and s.get("url")]
    out = []
    for s in reg:
        meta = " · ".join(filter(None, [esc(s.get("holder") or ""),
                                        esc(s["registration"]), esc(s.get("year", ""))]))
        out.append("\n".join([
            '%s<div class="patent-item">' % i,
            '%s  <div class="patent-title">%s</div>' % (
                i, esc(s.get("name_kr") or s.get("name_en"))),
            '%s  <div class="patent-meta">%s</div>' % (i, meta),
            "%s</div>" % i,
        ]))
    if tools:
        out.append('%s<p class="section-label" style="margin-top:36px">'
                   "// deployed_tools</p>" % i)
        for s in tools:
            name = esc(s.get("name_kr") or s.get("name_en"))
            title = ('<a href="%s" target="_blank" rel="noopener">%s</a>'
                     % (esc(s["url"]), name))
            meta = " · ".join(filter(None, [
                esc(s.get("description_kr") or s.get("description_en") or ""),
                esc(s.get("year", ""))]))
            out.append("\n".join([
                '%s<div class="patent-item">' % i,
                '%s  <div class="patent-title">%s</div>' % (i, title),
                '%s  <div class="patent-meta">%s</div>' % (i, meta),
                "%s</div>" % i,
            ]))
    return out


def block_agentwork(d: dict, i: str) -> list[str]:
    """AI-agent lectures and engagements, opted in with `lab_page: true`."""
    out = []
    talks = [t for t in d["invited_talks"] if t.get("lab_page")]
    for t in talks:
        when = esc(t.get("date") or t.get("year", ""))
        out.append("\n".join([
            '%s<div class="patent-item">' % i,
            '%s  <div class="patent-title">%s</div>' % (
                i, esc((t.get("title_kr") or t.get("title") or "").rstrip("."))),
            '%s  <div class="patent-meta">%s · %s</div>' % (
                i, esc(t.get("venue_kr") or t.get("venue", "")), when),
            "%s</div>" % i,
        ]))
    engagements = [c for c in d["consulting"] if c.get("lab_page")]
    if engagements:
        out.append('%s<p class="section-label" style="margin-top:36px">'
                   "// engagements</p>" % i)
        for c in engagements:
            when = esc(c.get("period") or c.get("year", ""))
            out.append("\n".join([
                '%s<div class="patent-item">' % i,
                '%s  <div class="patent-title">%s</div>' % (
                    i, esc(c.get("org_kr") or c.get("org_en", ""))),
                '%s  <div class="patent-meta">%s · %s · %s</div>' % (
                    i, esc(c.get("kind_kr") or c.get("kind_en", "")),
                    esc(c.get("topic_kr") or c.get("topic_en", "")), when),
                "%s</div>" % i,
            ]))
    return out


def block_links(d: dict, i: str) -> list[str]:
    """Contact cards for the full CV and ORCID."""
    p = d["person"]
    cards = []
    cv_url = (p.get("links") or {}).get("cv")
    if cv_url:
        cards.append(("// cv", cv_url, "full_cv"))
    if p.get("orcid"):
        cards.append(("// orcid", "https://orcid.org/%s" % p["orcid"], p["orcid"]))
    out = []
    for label, url, text in cards:
        out.append("\n".join([
            '%s<div class="contact-card">' % i,
            '%s  <div class="label">%s</div>' % (i, esc(label)),
            '%s  <div class="val"><a href="%s" target="_blank" rel="noopener">%s</a></div>'
            % (i, esc(url), esc(text)),
            "%s</div>" % i,
        ]))
    return out


BLOCKS = {
    "PUBLICATIONS": block_publications,
    "PROFILE": block_profile,
    "SOFTWARE": block_software,
    "AGENTWORK": block_agentwork,
    "LINKS": block_links,
}


# --------------------------------------------------------------------------

def sync(lab_dir: str, check: bool = False, source: str | None = None) -> int:
    index = os.path.join(lab_dir, "index.html")
    if not os.path.exists(index):
        sys.stderr.write("no index.html at %s\n" % index)
        return 2

    d = cvdata.load(source)
    html = original = io.open(index, encoding="utf-8").read()

    applied, skipped = [], []
    for name, render in BLOCKS.items():
        start = "<!-- CV:%s:START -->" % name
        end = "<!-- CV:%s:END -->" % name
        if start not in html or end not in html:
            skipped.append(name)
            continue
        m = re.search(re.escape(start) + r".*?" + re.escape(end), html, flags=re.S)
        indent_m = re.search(r"\n([ \t]*)" + re.escape(start), html)
        i = indent_m.group(1) if indent_m else "      "
        body = render(d, i)
        new = "\n".join([start, i + WARN] + body + [i + end])
        html = html.replace(m.group(0), new)
        applied.append((name, len(body)))

    # The boot animation announces a record count. Keep it honest — it drifted
    # out of step once already, when a paper was dropped during a redesign.
    n_pubs = len(site_rows(d))
    html, hits = re.subn(r"(Mounting publication index \()\d+( records\))",
                         r"\g<1>%d\g<2>" % n_pubs, html)

    if skipped:
        sys.stderr.write("  note: no markers for %s — skipped\n" % ", ".join(skipped))
    if not hits:
        sys.stderr.write("  note: boot-sequence record count not found — skipped\n")

    if html == original:
        print("lab page already in sync (%s)"
              % ", ".join("%s=%d" % (n, c) for n, c in applied))
        return 0
    if check:
        sys.stderr.write("lab page is OUT OF SYNC with cv.yaml\n")
        return 1

    io.open(index, "w", encoding="utf-8", newline="\n").write(html)
    print("updated %s — %s · generated %s"
          % (index, ", ".join("%s=%d" % (n, c) for n, c in applied), stamp(d)))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync CV data into the lab website")
    ap.add_argument("--lab", required=True, help="path to the sunwhikim_lab_page checkout")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if out of sync, change nothing")
    ap.add_argument("--source", default=None, help="path to cv.yaml")
    args = ap.parse_args()
    return sync(args.lab, check=args.check, source=args.source)


if __name__ == "__main__":
    sys.exit(main())
